add like model and sample_data
YoungSong99/photogram-industrial pull request #5
Opened 2024-07-02 20:20 UTC by YoungSong99

2024-07-02 20:31 UTC, jrzricardo approved these changes
solid code there bud

2024-07-02 20:48 UTC, thierrychau requested changes
Great job so far, I left a minor comment below. Also, I think it's missing a lot of the changes that should have been in this PR, looks like the other scaffold generations are not in here. Can you fix this? Thanks!

2024-07-02 20:48 UTC, thierrychau commented on app/models/like.rb
> +  belongs_to :photo, counter_cache: true
Can you add a validation to make sure a user can only like the same photo once?

2024-07-02 21:56 UTC, thierrychau requested changes
Great job, I see the extra effort you put in to go above and beyond. However, we want to keep pull request very tight and concise, since it's also about collaboration. Can you see the comments below? Thanks!

2024-07-02 21:56 UTC, thierrychau commented on app/assets/stylesheets/application.css
It's generally good practice to keep pull request focused on the task assigned to you.
This makes pull requests with clean diffs, and makes it easier for reviewer also! Also, in bigger project, someone else might be responsible for frontend. 

Can I ask you to remove this? Thanks!

2024-07-02 21:56 UTC, thierrychau commented on app/controllers/photos_controller.rb
> +    @photo.owner_id = current_user.id
Great job!

2024-07-02 21:56 UTC, thierrychau commented on app/controllers/photos_controller.rb
> +
Remove extra line

2024-07-02 21:56 UTC, thierrychau commented on app/views/devise/confirmations/new.html.erb
We want to keep this PR as clean as possible. Can you move these devise views outside of this PR?

2024-07-03 02:41 UTC, thierrychau approved these changes
Great job, you are good to merge. Thanks for the edits and your understanding!

2024-07-03 14:42 UTC, merged